export const environment = {
  production: false,
  unsplashApiKey: 'your_unsplash_api_key_here',
};

// IMPORTANT SECURITY NOTE:
// For production, NEVER store API keys in the frontend code.
// Instead, create a backend proxy service that handles API calls
// and keeps the keys secure on the server side.
//
// Example backend proxy:
// Frontend → POST /api/plant-info → Backend → Google AI API
//
// This file is auto-generated from .env by scripts/set-env.js
// DO NOT edit this file directly - edit .env instead and run the script.
